(ns main.rules-section.data)

(def skill-checks-details
  {:overview
   {:header "Overview"
    :body "\tSkill checks should be made when a character’s actions have a reasonable chance of both failure and success and when failure would come at a cost. If it is impossible for a skill check to fail or to succeed, then there is nothing to check. If a skill check has a reasonable chance of both success and failure but there is no cost for the actions either way, then the character could just continue to try again until they succeed. Ultimately, it is up to the GM’s discretion when a skill check should be called for. When a skill check is called for, you will use your character’s stats to determine the check’s base dice pool. The base dice pool may then be modified by bonuses and penalties. Once the base dice pool has been modified, then the dice are rolled and the results are compared to a target number which represents the difficulty of the actions you are taking."
    :example "\tFor example, say the dice pool you roll for a skill check is 3d6 and you roll a 1, 3, and 4. The result of the check would be the 4 and the other two numbers are ignored."}

   :base-dice-pool
   {:header "Base Dice Pool"
    :body "\tWhen a check is called for, the GM will determine which of your stats is most relevant to the task at hand and the dice pool provided under that stat will become your base dice pool. For example, if you are trying to climb a cliffside, the GM may ask for a check using your coordination skill. If your coordination skill is 2d8, then your base dice pool would be two 8-sided dice."}

   :benefits-and-detriments
   {:header "Benefits and Detriments"
    :body "\tCircumstances and resources can affect skill checks beneficially or detrimentally. Beneficial effects grant dice bonuses and flat bonuses while detrimental effects inflict dice penalties and flat penalties. Dice bonuses and dice penalties alter your chances of success by increasing or decreasing the number of dice you roll. They are represented in the format of \"+1d\" for bonuses and \"-1d\" for penalties. On the other hand, flat penalties alter the limits of what you can accomplish by increasing or decreasing the result of the roll. They are represented in the format of \"+1\" or \"-1\". When bonuses and penalties of the same type are applied to a check, they cancel each other out and the final number is then applied to the dice pool. If a dice penalty would cause you to roll zero dice, instead, roll one die of the next size down.\n\tSometimes bonuses and penalties will be applied to a check after you have rolled the dice but before the check is resolved. If a dice bonus is applied after you roll your dice but before the roll is resolved, then roll the bonus dice and compare the result of the dice pool in question to your bonus dice result and take the higher of the two. If a dice penalty is inflicted after you roll all of your dice but before the roll is resolved, then roll the penalty dice one at a time and compare the result to the previous result. The die that is numerically closest to the penalty die you rolled is removed from the roll, rounding unfavorably, and then repeat this process with any remaining penalty dice. If you have penalty dice remaining when there is only one die left in the dice pool in question, then roll the next penalty die and take the lower of the two results. Continue this process until there are no penalty dice left."
    :example "\tSay you are making an attack with a Coordination check of 2d8 and you gain a +2d and a +2 bonus. The check would then be 4d8 +2. Say that you instead are inflicted with a -2d and -2 penalty. The check would then be 1d6 -2 since the first -1d penalty reduces it to 1d8 and the next -1d penalty reduces 1d8 to 1d6.\n\tSay you have already rolled your 2d8 Coordination check and you rolled a 3 and a 7 at the beginning of a moment, but before your attack is resolved, an ally assists you and grants you +1d. At the point that you resolve your check, roll an additional 1d8 and say you roll an 8. The result of that check would then be 8 instead of 7. On the other hand, if a -1d penalty was inflicted between you rolling a 3 and a 7 and resolving that check, then roll 1d8 and remove the closest dice value. If the penalty die rolls a 2 or a 4 for example, then it removes the 3 from the roll and the end result remains at 7. If the penalty die rolls a 5, 6, or 8, for example, then the 7 is removed and the end result becomes a 3."}

;;    :complex-actions
;;    {:header "Complex Actions"
;;     :body "\tAfter bonuses and penalties are applied but before the roll is made, you can choose how complex you would like your action to be. Actions are made complex by splintering the base dice pool into multiple fragmentary pools. Each of these fragmentary pools are counted as separate results for the purposes of resolving the check. This allows you to attempt multiple endeavors where you would usually only be able to attempt one. A common example of this is making multiple attacks against an enemy or attacking different enemies simultaneously. If you choose to splinter your base dice pool, each of the fragmentary dice pools must contain at least two dice. Some resources place higher limitations on the size of the fragmentary dice pools you can create. Flat bonuses and penalties must be distributed as evenly as possible amongst the fragmentary dice pools."
;;     :example "\tSay you are casting a spell with an Exertion check of 4d6. You may choose to split the spell and target two separate creatures by rolling two separate fragmentary pools of 2d6. You could not, however, split the spell 4 times and make 4 rolls of 1d6."}

;;    :careful-and-reckless-actions
;;    {:header "Careful and Reckless Actions"
;;     :body "\tThe final modification that can be made to a dice pool before rolling is choosing to be careful or reckless. If you choose to act recklessly, then two dice of the same size in the same dice pool may be combined into a single die of the next highest size. On the other hand, if you choose to act carefully, then a single die may be split into two dice of the next smallest size. You can choose your degree of carefulness or recklessness by splitting or combining only some of the dice in the dice pool. In this case, you will end up with a dice pool containing dice of different sizes. This makes no difference in the roll. You will still simply roll all of the dice in the pool and take the highest result."
;;     :example "\tSay you make an attack with a Coordination check of 4d8. You could act recklessly and instead roll 2d10 or act carefully and roll 8d6. You could act partially reckless and roll 2d8 + 1d10 and take the highest result of the three dice. You could also act partially carefully and roll 3d8 + 2d6 and take the highest result of the five dice. If you chose to splinter your base dice pool into two fragmentary pools of 2d8, you may still choose to act recklessly or carefully with respect to each of those fragmentary pools. Your choice to act carefully or recklessly comes after splintering your dice pool, however, so you could not act carefully to roll 8d6 and then splinter that dice pool into four fragmentary pools of 2d6."}

   :passive-checks
   {:header "Passive Checks"
    :body "\tPassive checks may be used by the GM to resolve situations where your character’s stats are relevant but your character doesn't need to do anything to resolve the situation. Checks to determine your character's level of knowledge on a topic or checks to notice something in your surroundings when you aren’t searching will commonly be made as passive checks. The GM will still determine a target number and choose which stats are most relevant, however, instead of modifying that dice pool and rolling those dice, you will add together the following three values to determine the result: half of the size of the dice that make up the dice pool, the number of dice in the dice pool, and the net value of all of the bonuses and penalties. This result cannot exceed the cumulative total of the size of dice that make up the dice pool and the net value of your flat bonuses and penalties. Once the result is determined, it is compared to the target number determined by the GM as usual."
    :example "\tSay you are recalling some bit of information with a reference document that grants you +2d +1 to your Recollection check of 1d8. Your base dice pool would become 3d8 +1. To calculate the passive result of this check, you would add 4 for half the dice size of the check, 3 for the number of dice you are rolling, and 1 for the flat bonus to the roll for an end result of 8. If the reference document instead granted +4d +1, then your base dice pool would become 6d8 +1. To calculate the passive result of this check, you would add 4 for half the dice size of the check, 6 for the number of dice you are rolling, and 1 for the flat bonus to the roll for an end result of 11, however, the check cannot exceed the size of your dice (8) plus the flat bonus (1). So the actual result would end up being 9."}})


(def encounters
  {:overview
   {:header "Overview"
    :body "\tAn encounter is a scene that is centered around a goal and obstacle where many of your actions require skill checks. One of the clearest examples of an encounter is combat. During combat, the most basic goal is survival, the obstacle to that goal is the creatures or characters that are trying to kill you. Most of your actions will relate to attacking, defending, or positioning which all frequently require skill checks. Other examples of scenes that may be counted as encounters are chase scenes, social functions, survivalist challenges, heists, and investigations. Encounters are the most structured portions of an adventure. Your GM may decide to run some encounters more casually just like they would any other part of the adventure, however, if they want to track the order of actions more carefully, then they may use the following structure."}

   :actions
   {:header "Actions"
    :body "\tThere are two types of actions: setup actions and engagement actions. Setup actions are small adjustments that don’t take much focus, time, or effort. Engagement actions are where the bulk of the encounter takes place and they will usually require much more from you and have a risk of failure. Generally speaking, if an action requires a check, then it is likely an engagement action and if an action only requires a passive check or no check at all, then it is likely a setup action. Engagement actions are further divided into initiations and reactions and you will most often take one of each. Initiations require you to have focus on a target, usually a creature, object, or zone, while reactions can only be used when you are the target, or in the target area, of another creature's initiation. Listed below are some examples of the two kinds of actions."
    :example (str "| Setup Actions |" (apply str (interleave (repeat "\n\t- ") ["Duck behind cover" "Fall prone" "Stand up" "Walk" "Focus"]))
                  "\n| Engagement Actions |" (apply str (interleave (repeat "\n\t- ") ["Cast a spell" "Attack with a weapon" "Grapple" "Disarm" "Climb" "Swim" "Jump" "Hide" "Provide first aid" "Block" "Parry" "Counterspell" "Guard mind" "Evade"])))}

;; Used for rules with complex and reckless actions 
;;    :moments
;;    {:header "Moments"
;;     :body "\tAfter the setup phase of a round is complete and initial bonuses and penalties have been added to everyone’s base dice pools, the first moment of the engagement phase begins. When a moment begins, anyone who would like to act in that moment may commit dice to the moment by setting them aside. You can choose to commit only a portion of your dice pool to the moment by splintering them from their current dice pool and you can also commit multiple fragmentary dice pools to a single moment. Once everyone has committed their dice, they may modify them by combining or splitting them and then everyone rolls their dice at the same time. The dice that have been rolled are resolved in the following manner:\n\t1. The dice pools with the fewest dice are resolved first.\n\t2. If two dice pools have the same number of dice, then the dice pool with the larger sized dice goes first.\n\t3. If the dice pools are identical, then the Players action is resolved first.\n This means that modifications to your dice pool may cause your actions to be resolved earlier or later than they otherwise would be resolved. Reckless actions will have fewer dice and so will be resolved earlier while careful actions will have more dice and so be resolved later. Once all of the rolls committed to a moment have been resolved, the next moment of the round begins and everyone who has dice remaining in their dice pool may choose to commit dice to the next moment following the same rules as in the prior moment."
;;     :example "\tIstrid (played by the Game Master) and Parcivel (played by the Player) have been in a life and death struggle and it comes down to this final moment. Istrid starts the moment by spending a full engagement action on an underhanded trick, kicking up dust into Parcivel's face while Parcivel spends an engagement action to make an attack with his rapier. Istrid has a base dice pool of 4d6 for a Coordination check and she commits all of her dice to the endeavor while Parcivel has a base dice pool of 4d8 and he only commits 2d8 to the moment. Since Parcivel is rolling fewer dice, his attack is resolved first and he rolls a 2d8 -> 5. Istrid chooses to take the major wound by not defending herself in order to keep her other engagement action for a followup attack. She rolls a 4d6 -> 5 and Parcivel spends his second engagement action to try evading the dust. He has a dice pool of 6d6 but chooses to splinter that pool and only commit 2d6 to this initial defense. He rolls a 2d6 -> 4 and so he fails and his vision is obscured giving him a -2d penalty to all checks that rely on vision. Since all of the committed dice have been resolved, we move on to the next moment.\n\tIstrid has a full engagement action left and Parcivel has 2d8 of his rapier attack and 4d6 of his evasion. Istrid attacks with 8d6 hoping to finish off Parcivel. She splits her action into three pools of 2d6, 2d6, and 4d6, and commits all of them to the moment hoping to wear out his remaining defenses and then deal a killing blow. Parcivel attacks with his remaining 2d8, but because his vision is obscured, he takes a -2d penalty reducing it to a roll of 1d6. This is the lowest number of dice and so it is resolved first. He rolls a 1d6 -> 3 and inflicts a minor wound on Istrid since the attack goes undefended. Istrid follows up with 2d6 -> 3, 2d6 -> 4, and 4d6 -> 6 and Parcivel attempts to defend against them. He splits his remaining evasion check of 4d6 into two pools of 2d6, however, this check also takes the -2d penalty. The penalty is distributed evenly between the two rolls dropping them both to 1d6. He rolls 1d6 -> 3 and 1d6 -> 2. He barely manages to slip by the first attack, tying with Istrid's roll, fails on the second roll taking a minor wound, and leaves the last attack result of 6 undefended taking a major wound. With Istrid's blade in his chest, Parcivel slumps to the ground lifeless."}

   :moments
   {:header "Moments"
    :body "\tAfter the setup phase of a round is complete and initial bonuses and penalties have been added to everyone’s base dice pools, the first moment of the engagement phase begins. When a moment begins, anyone who would like to act in that moment may commit dice to the moment by setting them aside. Everyone who has chosen to commit dice rolls them at the same time. The dice that have been rolled are resolved in the following manner:\n\t1. The dice pools with the fewest dice are resolved first.\n\t2. If two dice pools have the same number of dice, then the dice pool with the larger sized dice goes first.\n\t3. If the dice pools are identical, then the Players action is resolved first.\n This means that modifications to your dice pool may cause your actions to be resolved earlier or later than they otherwise would be resolved. Once all of the rolls committed to a moment have been resolved, the next moment of the round begins and everyone who has dice remaining may choose to commit them to the next moment following the same rules as in the prior moment."
    :example "\tIstrid (played by the Game Master) and Parcivel (played by the Player) have been in a life and death struggle and it comes down to this final moment. Istrid starts the moment by spending a full engagement action on an underhanded trick, kicking up dust into Parcivel's face while Parcivel spends an engagement action to make an attack with his rapier. Istrid has a base dice pool of 4d6 for a Coordination check while Parcivel has a base dice pool of 4d8. Since they are rolling the same number of dice, Parcival's attack is resolved first since he is rolling d8s while Istrid is rolling d6s. He rolls a 4d8 -> 7. Istrid chooses to take the major wound by not defending herself in order to keep her other engagement action for a followup attack. She rolls a 4d6 -> 5. Parcivel has an evasion dice pool of 4d6 but recognizes that a followup attack is likely coming so he chooses not to defend against Istrid's dust cloud. He automatically fails and his vision is obscured giving him a -2d penalty to all checks that rely on vision. Since all of the committed dice have been resolved, we move on to the next moment.\n\tIstrid and Parcival both have an engagement action remaining. Istrid attacks with 8d6 hoping to finish off Parcivel while Parcivel chooses not to attack and instead preserve the engagement action to defend himself. Istrid attacks with 8d6 -> 6 and Parcivel attempts to defend against them with his evasion check of 4d6. However, because he is partially blinded by the dust, he takes a -2d penalty and instead rolls 2d6 -> 2. Istrid's attack deals a major wound. With Istrid's blade in his chest, Parcivel slumps to the ground lifeless."}

;;    :rounds
;;    {:header "Rounds"
;;     :body "\tThe in-game duration of a round depends on the encounter you are involved in. In the case of small scale combat, a round will usually take about five to ten seconds, whereas in something like a social encounter, a round may take twenty minutes or an hour or even longer. Rounds are made up of two phases: the setup phase and the engagement phase. During the setup phase, creatures will have two setup actions that they can use to prepare themselves for the engagements that are to come. This phase will begin with everyone either declaring their current focus or spending a setup action to take the focus action, starting with the Game Master. If you already have focus on a creature, object, or location, you do not need to take the focus action again to maintain that focus, however, you can only maintain focus on one creature, object, or location at a time. You can also only focus a target if it is within line of sight and you immediately lose focus on your target once it is no longer in line of sight. Once everyone has declared their focus, then everyone is given the opportunity to use their remaining setup actions.\n\tAfter the setup phase ends, the first moment of the engagement phase begins. During the engagement phase, you will have two engagement actions which you can use to attempt to overcome the obstacles you have focused. You may take additional setup actions during the engagement phase as part of your engagement actions, however, each one of these setup actions inflicts a -1d penalty on both of your engagement actions. This penalty is applied even if you did not use either of your two setup actions in the setup phase. You may sacrifice one of your engagement actions to prevent these penalties from being applied to your other engagement action. You cannot take more than six setup actions in a round and you can’t take more than two setup actions in a moment. This phase will usually involve traversing significant obstacles by climbing, swimming, jumping, etc., using items, attacking and defending, or various forms of persuasion. The round ends once all of the engagement actions have been resolved or when a moment passes where no dice were rolled for engagement actions."
;;     :example "\tIstrid (played by the Game Master) and Caelif (played by the Player) are about to be locked in mortal combat with one another as Istrid has slain Caelif's brother in front of him. A new round begins with the setup phase and the Game Master begins with spending a setup action to shift focus onto Caelif and the Player declares that they are maintaining focus on Istrid from a previous round. Istrid spends her last setup action of the setup phase to draw her second weapon from its sheath. Caelif spends each of his setup actions to move towards Istrid. They are two zones away from one another at this point, so his first movement brings him into an adjacent zone with Istrid and his second setup action moves him into the same zone as Istrid. Now that neither of them have any setup actions remaining, the first moment of the engagement phase begins.\n\tNeither of them decide to take any setup actions in this moment and Caelif decides to spend both of his engagement action to make two Coordination checks of 6d6 with his short sword committing all of the dice to this moment. Istrid chooses not to defend against the 1 and takes a minor wound but she spends an engagement action to make a Reflexes check of 6d8 to evade the others. She splinters her dice pool into 3 fragmentary pools of 2d8 and acts carefully, normally, and recklessly in order to roll 4d6, 2d8, and 1d10 in response to the 5, 6, and 8 respectively. While defending against the attack result of 5, Istrid manages to roll 4d6 -> 6 and avoids taking any damage. While defending against the attack result of 6, Istrid gets an unlucky result of 2d8 -> 4 and takes another minor wound. While defending against the attack result of 8, she rolls a 1d10 -> 1 and takes a major wound. The first moment ends leaving Istrid with a full engagement action and Caelif with nothing.\n\tCaelif realizes he didn't deal enough damage and is in trouble since he has taken many wounds already and so he spends two setup actions to move two zones away and Istrid spends two setup actions to follow. She knows that Caelif is on his last leg and so she spends an Engagement action to make a Coordination check of 8d6 but since she took two setup actions, this engagement action is inflicted with a -2d penalty bringing it down to 6d6. From there, Istrid splinters the dice pool into three fragmentary dice pools of 2d6. She commits all of the dice to this moment since she knows he has no engagement actions left to defend himself with. In the end, she rolls 2d6 -> 2, 2d6 -> 4, and 2d6 -> 5. All of these attacks are undefended and so Caelif takes one minor wound and two major wounds. More than enough to kill him outright."}

   :rounds
   {:header "Rounds"
    :body "\tThe in-game duration of a round depends on the encounter you are involved in. In the case of small scale combat, a round will usually take about five to ten seconds, whereas in something like a social encounter, a round may take twenty minutes or an hour or even longer. Rounds are made up of two phases: the setup phase and the engagement phase. During the setup phase, creatures will have two setup actions that they can use to prepare themselves for the engagements that are to come. This phase will begin with everyone either declaring their current focus or spending a setup action to take the focus action, starting with the Game Master. If you already have focus on a creature, object, or location, you do not need to take the focus action again to maintain that focus, however, you can only maintain focus on one creature, object, or location at a time. You can also only focus a target if it is within line of sight and you immediately lose focus on your target once it is no longer in line of sight. Once everyone has declared their focus, then everyone is given the opportunity to use their remaining setup actions.\n\tAfter the setup phase ends, the first moment of the engagement phase begins. During the engagement phase, you will have two engagement actions which you can use to attempt to overcome the obstacles you have focused. You may take additional setup actions during the engagement phase as part of your engagement actions, however, each one of these setup actions inflicts a -1d penalty on both of your engagement actions. This penalty is applied even if you did not use either of your two setup actions in the setup phase. You may sacrifice one of your engagement actions to prevent these penalties from being applied to your other engagement action. You cannot take more than six setup actions in a round and you can’t take more than two setup actions in a moment. This phase will usually involve traversing significant obstacles by climbing, swimming, jumping, etc., using items, attacking and defending, or various forms of persuasion. The round ends once all of the engagement actions have been resolved or when a moment passes where no dice were rolled for engagement actions."
    :example "\tIstrid (played by the Game Master) and Caelif (played by the Player) are about to be locked in mortal combat with one another as Istrid has slain Caelif's brother in front of him. A new round begins with the setup phase and the Game Master begins with spending a setup action to shift focus onto Caelif and the Player declares that they are maintaining focus on Istrid from a previous round. Istrid spends her last setup action of the setup phase to draw her second weapon from its sheath. Caelif spends each of his setup actions to move towards Istrid. They are two zones away from one another at this point, so his first movement brings him into an adjacent zone with Istrid and his second setup action moves him into the same zone as Istrid. Now that neither of them have any setup actions remaining, the first moment of the engagement phase begins.\n\tNeither of them decide to take any setup actions in this moment and Caelif decides to spend both of his engagement action to make two Coordination checks of 4d6 with his short sword committing all of the dice to this moment. Istrid spends both of her engagement actions to defend against these attacks. Caelif rolls his first attack of 3d6 -> 5 and Istrid defends herself with an evasion of 3d6 -> 4 and takes a minor wound. Caelif's second attack of 3d6 -> 2 goes undefended by Istrid as she chooses to simply take the minor wound. The first moment ends leaving Istrid with a full engagement action and Caelif with nothing.\n\tCaelif realizes he didn't deal enough damage and is in trouble since he has taken many wounds already and so he spends two setup actions to move two zones away and Istrid spends two setup actions to follow. She knows that Caelif is on his last leg and so she spends an Engagement action to make a Coordination check of 8d6 but since she took two setup actions, this engagement action is inflicted with a -2d penalty bringing it down to 6d6. She commits all of the dice to this moment since she knows he has no engagement actions left to defend himself with. In the end, she rolls 6d6 -> 6. The attack goes undefended so Caelif takes a major wound. It's just enough to finish him"}})
 

(def damage
  {:overview
   {:header "Overview"
    :body "\tBoth in and out of encounters, your character will have to react to events around them in an attempt to prevent harm to themself. Often times, when these reactions fail, your character will take damage. This damage is tracked separately for each of the four domains: physical, spiritual, mental, and social. As damage accumulates in each of the domains, you will be inflicted with more and more serious conditions."
    :example nil}

   :injuries
   {:header "Injuries"
    :body "\tIf an attack targets you and the result is equal to or greater than your reaction, then you take a minor injury. If the attack roll is equal to or greater than the reaction roll + 3, then you take a major injury. When you are inflicted with an injury, record the severity of the injury and the domain in which it was inflicted. It may also help to keep a running total of the points of damage you have in each domain. Minor injuries inflict one point of damage while major injuries inflict two points of damage."}

   :conditions
   {:header "Conditions"
    :body "\tThere are three conditions that can apply to each domain that are inflicted on your character as they take increasing numbers of injuries: Wounded, Incapacitated, and Dead. You will make health checks to determine when these conditions are applied and the health check for each domain is that domain's continuation skill. If you receive an injury in a domain and the new total number of injuries exceeds half of the passive result of your health check rounded favorably, then you become inflicted with the Wounded condition in that domain. If you are inflicted with the Wounded condition and you take further damage in that domain, you must make a health check for that domain where the target number is equal to the new damage total. If your health check fails, then you become inflicted with the Incapacitated condition in that domain. If at any point, the total damage in a domain exceeds your maximum possible roll, then you are inflicted with the final condition in that domain - Dead. Whenever your wounds heal, look at your most severe condition in that domain. If you rolled to receive that condition, then roll a health check now where the target number is equal to your new damage total. If you succeed, then remove the condition. If the condition was received as a result of passing a threshold, then compare your new damage total to the threshold. If it is equal to or lesser than the damage threshold, then remove the condition. If inflicted with the Death condition in the Physical, Spiritual, or Mental domain, your character is no longer playable unless there is some process or item that specifically reverses the condition. The Death condition in the Social domain is relative to the circumstances in which it was acquired and so your character is still playable, however, the individuals that you are “dead to” so to speak may never want to interact with you again or they may become hostile to you."
    :example "\tSay you have a Continuation stat of 3d8 and you are attacked by a band of goblins. They strike at you and deal 3 minor wounds and 1 major wound for 5 points of damage total. Your continuation stat has a passive result of 7 (3d8 = (3 + half of 8) = 7) so 5 just passes the threshold of half your passive rounded up, so you gain your first condition of Wounded. You make a run for it but one of the goblins pulls out a sling and makes two attacks on you, each dealing a minor wound. You roll your health check based off of your Continuation stat of 3d8 twice for each wound and get 3d8 -> 8 and 3d8 -> 5. The first health check is successful since your roll of 8 is equal to or higher than your total damage at that point which was 6 points of damage. Your second health check, however, is unsuccessful since the 5 you rolled did not equal or exceed your total damage at that point which was 7. You gain your second condition of Incapacitated and fall unconscious.\n\tYou wake up to find that you are being cooked alive! Restrained and hanging right above the flames with nobody to save you, you take one point of damage per round. You make a health check of 3d8 -> 8 and manage to remain conscious for a moment longer as you struggle against your bonds, however, another point of damage puts your total at 9 which exceeds your maximum roll. You are inflicted with the final condition of Death, never to be heard from again. Though you do make for a tasty snack for all of those goblins!" }

   :recovery
   {:header "Recovery"
    :body "\tMinor injuries will heal naturally after 2 days while major injuries will heal naturally after 1 week. You may come across items or techniques that can be used to heal injuries quicker than through natural processes."}})

(def conditions
  {:wounded {:header "Wounded"
             :body {:effect "As a result of the injuries you have accumulated, your performance in a particular domain has diminished. While wounded, a -1d penalty is applied to all checks made in the domain you are wounded in."
                    :duration "This condition lasts until the total injuries in the relevant domain are equal to or lower than the threshold determined by that domain's health check."}}
   :incapacitated {:header "Incapacitated"
                   :body {:effect "You have accumulated enough injuries that your character is no longer in control of their body, mind, spirit, or reputation. When this condition is inflicted in the physical, spiritual, or mental domain, your character becomes unconscious, despondent, or unstable, respectively. You have no control over your character in any of these circumstances. In the case of social incapacitation, people may avoid associating with you or may ignore you completely."
                          :duration "Whenever your wounds heal, make a health check where the target number is your new damage total. If you succeed, then this condition is removed."}}
   :dead {:header "Dead"
          :body {:effect "You have accumulated more injuries than your body, mind, spirit, or reputation can handle. When this condition is inflicted in the physical, spiritual, or mental domain, the injuries accumulated in those domains no longer heal naturally over time. In the case of the social domain, your relationships with specific individuals or groups may be permanently severed and trying to interact with them may cause them to become hostile."
                 :duration "Unless a certain circumstance, process, or item says otherwise, this condition is permanent."}}
   :exhausted {:header "Exhausted"
               :body {:effect "Whether through over-exertion, sickness, or some other unfortunate circumstance, you have become exhausted and your overall capabilities are diminished. This condition can be applied any number of times adding additional levels of exhaustion. Each level of exhaustion inflicts a -1d penalty on all of your checks"
                      :duration "Six hours of uninterrupted sleep removes one level of exhaustion."}}
   :surprised {:header "Surprised"
               :body {:effect "Events have unfolded that were so unexpected that it takes your mind a bit to catch up. You cannot take any actions while surprised."
                      :duration "The surprise fades away after a few seconds."}}
   :blinded {:header "Blinded"
             :body {:effect "Some damage or barrier prevents you from seeing. Actions that depend on your sense of sight will receive penalties as determined by the Game Master."
                    :duration "Your sense of sight returns once the barrier is removed or damage healed."}}
   :deafened {:header "Deafened"
              :body {:effect "Some damage or barrier prevents you from hearing. Actions that depend on your sense of hearing will receive penalties as determined by the Game Master."
                     :duration "Your sense of hearing returns once the barrier is removed or damage healed."}}
   :constrained {:header "Constrained"
                 :body {:effect "You have become tangled, tied, or grappled and your movement is restricted. Actions that depend on your ability to move will receive penalties as determined by the Game Master."
                        :duration "Your freedom of movement returns when the restraints are removed."}}
   :frightened {:header "Frightened"
                :body {:effect "Your instinctual desire to preserve your life and well-being take over in the face of great danger. You cannot move closer to where you believe the source of your fear is."
                       :duration "This effect lasts until the source of your fear takes a major wound or until you deal any damage to it."}}})

(def stats
  {:coordination "Coordination represents a creature's physical strength, flexibility, and control. A creature with high coordination will hit harder and faster and be able to perform impressive feats of athleticism and acrobatics."
   :reflexes "Reflexes represents the speed and accuracy of a creature's reactions. A creature with high reflexes will be able to defend themself from incoming attacks much more reliably."
   :endurance "Endurance represents how much of a beating a creature can take as well as their resistance to sickness, disease, and exhaustion. A creature with high endurance will manage to survive where most other would not."
   :exertion "Exertion represents the strength of a creature's sense of self. A creature with high exertion is capable of handling enormous amounts of aethereal energy without fear of being consumed by it."
   :instinct "Instinct represents the strength and reliability of a creature's gut reactions. A creature with high instinct is very sensitive to the constantly shifting aether and are able to block out or reinforce the magic that touches their spirit."
   :perseverance "Perseverance represents a creature's ability to maintain their sense of self in the face of doubt and temptation. A creature with high perseverance is able to absorb large amounts of foreign aethereal energy without losing themself to the chaos."
   :concentration "Concentration represents a creature's ability to focus on a single task and avoid distractions. A creature with high concentration is able to accomplish more impressive feats with greater efficiency."
   :recognition "Recognition represents a creature's attention to detail. A creature with high recognition will often be able to notice the small things that others find insignificant. They are attentive to their surroundings and usually have great memories."
   :comprehension "Comprehension represents a creature's ability to absorb and retain information. A creature with high comprehension is better able to understand the underlying principles of that which they are learning often causing them to pick up skills quickly and can make them great teachers."
   :persuasion "Persuasion represents a creature's ability to sway the dispositions of others through charm, intimidation, or deception. A creature with high persuasion is able to get what they want from people without resorting to violence."
   :insight "Insight represents how well a creature picks up on the many unspoken facets of a social environment. A creature with high insight can often discern the true motives and character of those they are interacting with."
   :connections "Connections represents how many relationships and affiliations a creature has, how deep those connections run, and how good they are at calling upon those connections for favors. A creature with high connections always knows a guy who knows a guy whether that is through a membership in a group, a trade deal they made years ago, or simply a friend they met throughout their journeys."})